### ISSUE TITLE
Subscripts in Text elements not rendering properly

### ISSUE THREAD

**Issue by arturo182** [openscopeproject/InteractiveHtmlBom#198]
KiCad nightly added support for having sub- and superscripts in schematics and in the PCB Text Elements, when you type Foo_{bar} you get "bar" as subscript, and for Foo^{bar} you get it as superscript.

Here's an example:
![image](https://user-images.githubusercontent.com/249082/99649938-19e5a800-2a55-11eb-8b49-25aee0200598.png)

![image](https://user-images.githubusercontent.com/249082/99649842-ffabca00-2a54-11eb-8b43-662cfbfd87d1.png)

These are currently not rendering properly in the BOM:

![image](https://user-images.githubusercontent.com/249082/99649898-0d614f80-2a55-11eb-8263-5d4cd13c2812.png)

KiCad version: 5.99.0-6923-g2a3e6ee1b5
InteractiveHtmlBom version: 2.3-33-g43e5

Not really a showstopper, but still a bug 🙂

**Comment by qu1ck** [comment]
Yeah I saw these added a while ago and seeing how subdued the effect is I though likely nobody would use it in pcbs, only on schematics. Of course, I was wrong.

KiCad's text rendering code is becoming more and more convoluted and what's worse, ever so slightly inconsistent between versions. Even things like overbar rendering, interline distance changed a bit in v6. I'll try to look for a way to get text as polyline object from kicad itself instead of trying to replicate it's rendering code in ibom. It might blow up the generated page size a bit but it's probably worth it.

**Comment by qu1ck** [comment]
Relevant MR in kicad https://gitlab.com/kicad/code/kicad/-/merge_requests/530
If that is accepted I have a patch ready that will make ibom's own implementation of text rendering obsolete.

**Comment by arturo182** [comment]
Awesome!

**Comment by qu1ck** [comment]
Wait a day for kicad's nightly to pick up my change and then update to latest.

**Comment by arturo182** [comment]
Thank you :)
