### ISSUE TITLE
FYI, no action needed: andreika-git-iBom with 3D view of the PCB

### ISSUE THREAD

**Issue by rusefillc** [openscopeproject/InteractiveHtmlBom#225]
Just FYI, maybe a useful feature proposal: 3D view of the PCB

at the moment it's merged into https://github.com/andreika-git/hellen-one/ and right now we are short on time to properly extract it as a separate tool or properly contribute it into the upstread.

https://rusefi.com/docs/ibom/hellen72b-ibom.html

![image](https://user-images.githubusercontent.com/48498823/108633823-68d01e80-7444-11eb-879d-9a119914bda6.png)

Implementation detail: we reuse a modified version of iBom-template.html

**Comment by qu1ck** [comment]
It's just a prerendered image drawn in the background. Nice, but I'd like to some day integrate [this](https://easyw.github.io/vrm360/).

**Comment by ozel** [comment]
a 3D assembly view would be so nice and especially useful for electronic beginners! For this beginner-friendly project I've used scripts to generate resistor models with colour bands:
![](https://raw.githubusercontent.com/ozel/DIY_particle_detector/master/hardware/V1.2/documentation/3D_bottom_electron.png)
In such 'educational' use cases, the 2D iBOM webview is currently a bit too abstract for beginners and not really necessary of course for experienced tinkerers due to the simplicity of the board.

Together with @Kasbah we've briefly experimented with using the SVG board outline for generating a simple 3D board model in javascript. The component 3D model files could then be loaded separately as needed instead of working with one big STEP file.

**Comment by qu1ck** [comment]
Cleaning up unactionable issues.
