### ISSUE TITLE
Conditional pin 1 highlighting?

### ISSUE THREAD

**Issue by kaysievers** [openscopeproject/InteractiveHtmlBom#374]
The pin 1 highlighting feature is really useful when placing components to remind that the part needs to be oriented correctly. There are many pin 1 marks though where the marking does not add any useful information.

1. Would it be possible to suppress the pin 1 highlighting for single pin footprints? Connectors and mechanical parts like standoffs do not need any attention regarding the part orientation.

2. Would it be possible to suppress the pin1 highlighting for 2 pin components which are unpolarized, like resistors/capacitors? What would be a good match to derive that property? The name of the schematic symbol?

Thanks a lot!

<img width="241" alt="Screenshot 2023-04-17 at 13 50 14" src="https://user-images.githubusercontent.com/1064936/232476320-40040c5a-285e-470b-92d0-f9d86b7b5374.png">

The majority of the pin 1 highlights in this picture would not be needed to place the component correctly.

**Comment by Funkenjaeger** [comment]
Trying to _infer_ whether a component is polarized or otherwise orientation-dependent based on symbol names/refdes/etc seems fraught with peril.  For instance, you said:
> components which are unpolarized, like resistors/capacitors

...but a lot of capacitors are polarized.  There's also no universal standard for reference designators, so any rule set you came up with would inevitably be wrong for someone else's use case.
Conditionally suppressing on the basis of a user-defined extra field would make more sense IMO - it wouldn't be automatic, but your intent would be unambiguous.

**Comment by qu1ck** [comment]
I don't see any harm in highlighting mounting hole's "pin" even if it's not useful. But there is an easy to implement solution that should reduce visual clutter: add an option to only show pin 1 for components that are highlighted.
So to see pin1 outline you would click the component or hover over it's row in the table. Thoughts?

**Comment by qu1ck** [comment]
For the lack of feedback I went ahead and implemented my idea. It's not exactly what you were asking for but still gives you control when pin1 is highlighted.
