### ISSUE TITLE
The silkscreen of unused components is not removed for .brd files

### ISSUE THREAD

**Issue by PrzemekBarczyk** [openscopeproject/InteractiveHtmlBom#475]
I'm using your project to generate interactive BOMs for the EAGLE program. I've noticed discrepancies in the output file depending on whether the input file is a .brd file or a .json file (generated with brd2json.ulp).

If a project has a variant with hidden components, the BOM generated from the .json file does not include these components in either the table or the schematic. In contrast, for .brd files, the hidden components are only excluded from the table but remain visible on the schematic.

Below, I’ve attached screenshots to illustrate these differences.

Are the described differences intentional design decisions? Does the project allow for variant configuration using .brd files so that hidden components are also excluded from the schematic?

Thank you!

![bom .json](https://github.com/user-attachments/assets/2f229a31-2f85-4839-b455-0492758e8d3a)
BOM obtained using .json

![bom .brd](https://github.com/user-attachments/assets/c4687779-ea2d-4fe6-a160-8960a0d03c9d)
BOM obtained using .brd

![image](https://github.com/user-attachments/assets/b8d8e617-d48d-4310-b880-7a7e2f724031)
.brd in EAGLE

**Comment by qu1ck** [comment]
Silkscreen is expected to not be removed because it does not magically disappear from the board if you don't solder the component. The rendering is supposed to represent how the actual board looks, including pads and silk markings.

Not sure why using the json method shows that behavior but that method ulp is not maintained afaik, use native .brd support.

**Comment by PrzemekBarczyk** [comment]
Thanks for the quick response!

**Comment by Funkenjaeger** [comment]
I've added an issue to the brd2json repo regarding the incorrect behavior with the ULP (footprints missing for unpopulated components) - just for posterity, as I'm not inclined to fix it presently.  As @qu1ck  said, the ULP is essentially OBE at this point due to native .brd/.fbrd support in ibom which has been in place for just shy of 2 years now, so I've gone ahead and archived that repo.
