### ISSUE TITLE
Saving the board picture

### ISSUE THREAD

**Issue by bms-2015** [openscopeproject/InteractiveHtmlBom#478]
Hello. 
Is it possible to do, please
 
1) When saving the board picture, no selected areas were marked on it?  (or optional (checkbox)) 

![Clipboard_11-02-2024_03](https://github.com/user-attachments/assets/37d1cfae-cc56-4993-ab89-0162a8bf3764)

2) Add option Mirroring when saving

3) The image when saving the picture was black and white (optional (checkbox))

![Clipboard_11-02-2024_05](https://github.com/user-attachments/assets/97230044-f295-4045-9b91-6dd02d101ecd)

4) Save in pdf with real PCB board size and calibration vertical and horizontal lines  (with pagination if it does not fit)  (optional (checkbox))

![Clipboard_11-02-2024_06](https://github.com/user-attachments/assets/68470c53-c2b0-4784-a1cd-87a7349ae1d2)

Of course, all this can be done manually in editors, but I think it would be useful to many users.

**Comment by qu1ck** [comment]
1) can be done
2) and 3) are not a bom tool's job, you should do it from your EDA where you can precisely control layers, colors, sizes, mirroring, etc.
4. is not feasible.

**Comment by qu1ck** [comment]
Again, if you want technical drawings for toner transfer manufacturing method, use appropriate tool for it. Ibom is not designed to provide precise and accurate drawings, it does not even support zones for easyeda, or custom fonts for text, it will never be accurate reflection of your design.
The drawing in ibom is there for your reference to populate the board during assembly, it does not meet the standards needed for manufacturing of the pcb itself.

Regarding pdf, it is not feasible without including a massive pdf library in every bom page, I can not use the lib from a cdn like in your example because ibom html pages need to work offline.

But looks like you know some javascript and if you use custom js you can add the functionality you want. If you manage to do it and are willing to share it I will gladly add it to the [wiki](https://github.com/openscopeproject/InteractiveHtmlBom/wiki/Customization)

**Comment by mMuck** [comment]
@bms-2015 I want to recommend the KiCad Board2Pdf Plugin (https://gitlab.com/dennevi/Board2Pdf) - here you could control nicely what layers should be in your PDF and with what colors.

Could this be closed?

**Comment by qu1ck** [comment]
Option to render the highlights on saved image can still be implemented (#1 on OP's list).
